[package]
name = "relay-server"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
relay-push = { path = "../relay-push" }
actix-web.workspace = true
actix-ws.workspace = true
futures-util.workspace = true
sqlx.workspace = true
redis.workspace = true
jsonwebtoken.workspace = true
ed25519-dalek.workspace = true
ring.workspace = true
uuid.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
base64.workspace = true
env_logger.workspace = true
log.workspace = true
subtle.workspace = true

[dev-dependencies]
actix-http.workspace = true
hex.workspace = true
tokio-tungstenite.workspace = true
tokio = { workspace = true, features = ["net", "io-util"] }
rsa = { workspace = true, features = ["getrandom"] }
jsonschema.workspace = true
futures-util = { workspace = true, features = ["sink"] }
